import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';

import Navbar from '@/components/ui/Navbar';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        <main className='container mx-auto my-5 h-full max-w-screen-lg'>
          {children}
        </main>
      </body>
    </html>
  );
}
